export  const CHANGE_PROJECT_REACTION_TYPE = "CHANGE_PROJECT_REACTION_TYPE";
export  const ENABLE_ANIMATION = "ENABLE_ANIMATION";
export  const CHANGE_FIGURE_VALUE = "CHANGE_FIGURE_VALUE";
export  const UPDATE_PROJECT_STATE = "UPDATE_PROJECT_STATE";
export  const ADD_FIGURE = "ADD_FIGURE";
export  const DELETE_FIGURE = "DELETE_FIGURE";
export  const SHOW_FIGURE_EDITOR = "SHOW_FIGURE_EDITOR";