export const CHANGE_PROJECT_REACTION_TYPE = "CHANGE_PROJECT_REACTION_TYPE";
export const ENABLE_ANIMATION = "ENABLE_ANIMATION";
export const CHANGE_FIGURE_VALUE = "CHANGE_FIGURE_VALUE";
export const UPDATE_PROJECT_STATE = "UPDATE_PROJECT_STATE";
export const ADD_FIGURE = "ADD_FIGURE";
export const ADD_PROJECT = "ADD_PROJECT";
export const DELETE_FIGURE = "DELETE_FIGURE";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const SHOW_FIGURE_EDITOR = "SHOW_FIGURE_EDITOR";
export const SET_CURRENT_PROJECT = "SET_CURRENT_PROJECT";
export const CHANGE_ACTIVE_SVG_FIGURE = "CHANGE_ACTIVE_SVG_FIGURE";
export const IMPORT_FIGURES_FROM_FILE = "IMPORT_FIGURES_FROM_FILE";
export const HANDLE_IMPORTED_PROJECT_FILE = "HANDLE_IMPORTED_PROJECT_FILE";
export const CHANGE_PROJECT_NAME = "CHANGE_PROJECT_NAME";

