export const CHANGE_PROJECT_REACTION_TYPE: string = "CHANGE_PROJECT_REACTION_TYPE";
export const ENABLE_ANIMATION: string = "ENABLE_ANIMATION";
export const CHANGE_FIGURE_VALUE: string = "CHANGE_FIGURE_VALUE";
export const UPDATE_PROJECT_STATE: string = "UPDATE_PROJECT_STATE";
export const ADD_FIGURE: string = "ADD_FIGURE";
export const ADD_PROJECT: string = "ADD_PROJECT";
export const DELETE_FIGURE: string = "DELETE_FIGURE";
export const DELETE_PROJECT: string = "DELETE_PROJECT";
export const SHOW_FIGURE_EDITOR: string = "SHOW_FIGURE_EDITOR";
export const SET_CURRENT_PROJECT: string = "SET_CURRENT_PROJECT";
export const CHANGE_ACTIVE_SVG_FIGURE: string = "CHANGE_ACTIVE_SVG_FIGURE";
export const IMPORT_FIGURES_FROM_FILE: string = "IMPORT_FIGURES_FROM_FILE";
export const HANDLE_IMPORTED_PROJECT_FILE: string = "HANDLE_IMPORTED_PROJECT_FILE";
export const CHANGE_PROJECT_NAME: string = "CHANGE_PROJECT_NAME";

